import type { JobSectorKey } from "../domain/taxonomy";
import type { SourceType } from "../domain/source";

/**
 * Verification state recorded for every manifest endpoint on the import date.
 * Only `verified` endpoints may be imported active. `stale` entries have a
 * current failure observation (404/400) or a known identifier mismatch;
 * `unverified` entries have not been re-verified. Both import paused.
 */
export type ManifestVerification = Readonly<{
  status: "verified" | "stale" | "unverified";
  date: string;
  evidenceUrl?: string;
  notes: string;
}>;

export type ManifestCompany = Readonly<{
  atsProvider?: string;
  careersUrl: string;
  configuration: Readonly<Record<string, unknown>>;
  crawlFrequencyMinutes: number;
  directorySectorKey: JobSectorKey;
  industry: string;
  name: string;
  needsBrowser?: boolean;
  slug: string;
  sourceType: SourceType;
  verification: ManifestVerification;
  websiteUrl: string;
}>;

export const MANIFEST_VERSION = 2;

/**
 * Versioned UK-relevant employer cohort.
 *
 * VERIFICATION (2026-08-12): seven endpoints are currently verified by a
 * bounded unauthenticated GET against the official public ATS job-board API.
 * Seventeen known-stale entries (Greenhouse/Lever/Ashby 404s, a SmartRecruiters
 * 400, four SmartRecruiters identifiers returning 200 with zero postings, and
 * the Accenture identifier change to Workday) and fifteen not-yet-re-verified
 * entries import as PAUSED. A source is never activated without a current
 * verification; nothing here claims all 39 entries are verified.
 */
export const employerManifest: readonly ManifestCompany[] = [
  {
    atsProvider: "Greenhouse",
    careersUrl: "https://boards.greenhouse.io/monzo",
    configuration: { greenhouseBoardToken: "monzo" },
    crawlFrequencyMinutes: 720,
    directorySectorKey: "technology_it",
    industry: "Banking / Technology",
    name: "Monzo",
    slug: "monzo",
    sourceType: "greenhouse",
    verification: {
      status: "verified",
      date: "2026-08-12",
      evidenceUrl: "https://boards-api.greenhouse.io/v1/boards/monzo/jobs?per_page=1",
      notes: "Verified 2026-08-12: bounded GET on the official Greenhouse board API returned 200.",
    },
    websiteUrl: "https://monzo.com",
  },
  {
    atsProvider: "Greenhouse",
    careersUrl: "https://boards.greenhouse.io/dropbox",
    configuration: { greenhouseBoardToken: "dropbox" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "technology_it",
    industry: "Technology",
    name: "Dropbox",
    slug: "dropbox",
    sourceType: "greenhouse",
    verification: {
      status: "verified",
      date: "2026-08-12",
      evidenceUrl: "https://boards-api.greenhouse.io/v1/boards/dropbox/jobs?per_page=1",
      notes: "Verified 2026-08-12: bounded GET on the official Greenhouse board API returned 200.",
    },
    websiteUrl: "https://www.dropbox.com",
  },
  {
    atsProvider: "Ashby",
    careersUrl: "https://jobs.ashbyhq.com/notion",
    configuration: { ashbyOrg: "notion" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "technology_it",
    industry: "Technology",
    name: "Notion",
    slug: "notion",
    sourceType: "ashby",
    verification: {
      status: "verified",
      date: "2026-08-12",
      evidenceUrl: "https://api.ashbyhq.com/posting-api/job-board/notion?includeCompensation=true",
      notes: "Verified 2026-08-12: bounded GET on the official Ashby posting API returned 200.",
    },
    websiteUrl: "https://www.notion.so",
  },
  {
    atsProvider: "Greenhouse",
    careersUrl: "https://boards.greenhouse.io/duolingo",
    configuration: { greenhouseBoardToken: "duolingo" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "technology_it",
    industry: "Consumer Technology",
    name: "Duolingo",
    slug: "duolingo",
    sourceType: "greenhouse",
    verification: {
      status: "verified",
      date: "2026-08-12",
      evidenceUrl: "https://boards-api.greenhouse.io/v1/boards/duolingo/jobs?per_page=1",
      notes: "Verified 2026-08-12: bounded GET on the official Greenhouse board API returned 200.",
    },
    websiteUrl: "https://www.duolingo.com",
  },
  {
    atsProvider: "Greenhouse",
    careersUrl: "https://boards.greenhouse.io/instacart",
    configuration: { greenhouseBoardToken: "instacart" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "consumer_fmcg_retail",
    industry: "Retail Technology",
    name: "Instacart",
    slug: "instacart",
    sourceType: "greenhouse",
    verification: {
      status: "verified",
      date: "2026-08-12",
      evidenceUrl: "https://boards-api.greenhouse.io/v1/boards/instacart/jobs?per_page=1",
      notes: "Verified 2026-08-12: bounded GET on the official Greenhouse board API returned 200.",
    },
    websiteUrl: "https://www.instacart.com",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/NationalGrid",
    configuration: { smartRecruitersCompany: "NationalGrid" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "engineering_energy_infrastructure",
    industry: "Energy",
    name: "National Grid",
    slug: "national-grid",
    sourceType: "smartrecruiters",
    verification: {
      status: "stale",
      date: "2026-08-12",
      notes:
        "Stale 2026-08-12: official SmartRecruiters postings API returns 200 with zero postings for this identifier. Paused until a valid official endpoint is verified.",
    },
    websiteUrl: "https://www.nationalgrid.com",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/Wise",
    configuration: { smartRecruitersCompany: "Wise" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "financial_services",
    industry: "Fintech",
    name: "Wise",
    slug: "wise",
    sourceType: "smartrecruiters",
    verification: {
      status: "verified",
      date: "2026-08-12",
      evidenceUrl: "https://api.smartrecruiters.com/v1/companies/Wise/postings?limit=1",
      notes: "Verified 2026-08-12: bounded GET on the official SmartRecruiters API returned 200.",
    },
    websiteUrl: "https://wise.com",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/Revolut",
    configuration: { smartRecruitersCompany: "Revolut" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "financial_services",
    industry: "Fintech",
    name: "Revolut",
    slug: "revolut",
    sourceType: "smartrecruiters",
    verification: {
      status: "stale",
      date: "2026-08-12",
      notes:
        "Stale 2026-08-12: official SmartRecruiters postings API returns 200 with zero postings for this identifier. Paused until a valid official endpoint is verified.",
    },
    websiteUrl: "https://www.revolut.com",
  },
  {
    atsProvider: "Greenhouse",
    careersUrl: "https://boards.greenhouse.io/robinhood",
    configuration: { greenhouseBoardToken: "robinhood" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "financial_services",
    industry: "Financial Services",
    name: "Robinhood",
    slug: "robinhood",
    sourceType: "greenhouse",
    verification: {
      status: "verified",
      date: "2026-08-12",
      evidenceUrl: "https://boards-api.greenhouse.io/v1/boards/robinhood/jobs?per_page=1",
      notes: "Verified 2026-08-12: bounded GET on the official Greenhouse board API returned 200.",
    },
    websiteUrl: "https://robinhood.com",
  },
  {
    atsProvider: "Workday",
    careersUrl: "https://careers.bankofamerica.com/en-us",
    configuration: {
      cxsEndpoint: "https://ghr.wd1.myworkdayjobs.com/wday/cxs/ghr/lateral-us",
    },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "financial_services",
    industry: "Investment Banking",
    name: "Bank of America",
    slug: "bank-of-america",
    sourceType: "workday",
    verification: {
      status: "verified",
      date: "2026-08-12",
      evidenceUrl: "https://ghr.wd1.myworkdayjobs.com/wday/cxs/ghr/lateral-us/jobs",
      notes:
        "Verified 2026-08-12: bounded POST against the official public Workday CXS jobs endpoint returned 200 with live postings.",
    },
    websiteUrl: "https://www.bankofamerica.com",
  },
  {
    atsProvider: "Workday",
    careersUrl: "https://search.jobs.barclays/",
    configuration: {
      cxsEndpoint:
        "https://External_Career_Site_Barclays.wd1.myworkdayjobs.com/wday/cxs/External_Career_Site_Barclays/External_Career_Site_Barclays",
    },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "financial_services",
    industry: "Banking",
    name: "Barclays",
    slug: "barclays",
    sourceType: "workday",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes:
        "Workday tenant host confirmed, but the public CXS jobs endpoint returned 422 on 2026-08-12; the tenant site configuration still needs verification. Imported paused until verified.",
    },
    websiteUrl: "https://www.barclays.co.uk",
  },
  {
    atsProvider: "Workday",
    careersUrl: "https://jobs.citi.com",
    configuration: {
      cxsEndpoint: "https://citi.wd5.myworkdayjobs.com/wday/cxs/citi/Citi",
    },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "financial_services",
    industry: "Banking",
    name: "Citi",
    slug: "citi",
    sourceType: "workday",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes:
        "Workday tenant host confirmed, but the public CXS jobs endpoint site name returned 404 on 2026-08-12; tenant discovery still needed. Imported paused until verified.",
    },
    websiteUrl: "https://www.citi.com",
  },
  {
    atsProvider: "Own careers platform (beesite API)",
    careersUrl: "https://careers.db.com/professionals/search-roles",
    configuration: {
      capture: {
        urlPatterns: ["**beesite.de/search/**"],
        jobArrayPaths: ["SearchResult.SearchResultItems"],
        apiUrl:
          "https://api-deutschebank.beesite.de/search/?data=%7B%22LanguageCode%22%3A%22en%22%2C%22SearchParameters%22%3A%7B%22FirstItem%22%3A1%2C%22CountItem%22%3A100%2C%22Sort%22%3A%5B%7B%22Criterion%22%3A%22PublicationStartDate%22%2C%22Direction%22%3A%22DESC%22%7D%5D%7D%7D",
      },
    },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "financial_services",
    industry: "Banking",
    name: "Deutsche Bank",
    needsBrowser: true,
    slug: "deutsche-bank",
    sourceType: "direct_html",
    verification: {
      status: "verified",
      date: "2026-08-12",
      evidenceUrl:
        "https://api-deutschebank.beesite.de/search/?data=%7B%22LanguageCode%22%3A%22en%22%2C%22SearchParameters%22%3A%7B%22FirstItem%22%3A1%2C%22CountItem%22%3A100%7D%7D",
      notes:
        "Verified 2026-08-12: the careers SPA loads jobs from the official public beesite JSON API; a rendered capture run returned 100 live postings with official application URLs.",
    },
    websiteUrl: "https://www.db.com",
  },
  {
    atsProvider: "SuccessFactors careers site",
    careersUrl: "https://experienced.kpmgcareers.co.uk/search/",
    configuration: {},
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "financial_services",
    industry: "Professional Services",
    name: "KPMG UK",
    slug: "kpmg-uk",
    sourceType: "direct_html",
    verification: {
      status: "verified",
      date: "2026-08-12",
      evidenceUrl: "https://experienced.kpmgcareers.co.uk/search/",
      notes:
        "Verified 2026-08-12: the experienced careers site server-renders real job listings over plain HTTP with official application URLs; a connector run returned live postings with populated locations.",
    },
    websiteUrl: "https://www.kpmg.com/uk",
  },
  {
    atsProvider: "UBS careers platform",
    careersUrl: "https://jobs.ubs.com/",
    configuration: {},
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "financial_services",
    industry: "Banking",
    name: "UBS",
    needsBrowser: true,
    slug: "ubs",
    sourceType: "direct_html",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes:
        "IP-level bot wall returned 403 even to a real browser on 2026-08-12, so no endpoint could be verified. Paused until IP diversity or another verified public endpoint is available.",
    },
    websiteUrl: "https://www.ubs.com",
  },
  {
    atsProvider: "Lloyds Banking Group talent site",
    careersUrl: "https://www.lloydsbankinggrouptalent.com/our-opportunities",
    configuration: {},
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "financial_services",
    industry: "Banking",
    name: "Lloyds",
    needsBrowser: true,
    slug: "lloyds",
    sourceType: "direct_html",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes:
        "No public jobs API found on 2026-08-12; the opportunity pages are server-rendered category pages without job listings. Paused until deeper discovery is completed.",
    },
    websiteUrl: "https://www.lloydsbankinggroup.com",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/BDO",
    configuration: { smartRecruitersCompany: "BDO" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "financial_services",
    industry: "Professional Services",
    name: "BDO",
    slug: "bdo",
    sourceType: "smartrecruiters",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes: "Not re-verified on 2026-08-12; imported paused until the endpoint is verified.",
    },
    websiteUrl: "https://www.bdo.co.uk",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/JanusHenderson",
    configuration: { smartRecruitersCompany: "JanusHenderson" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "investment_banking_asset_management",
    industry: "Asset Management",
    name: "Janus Henderson",
    slug: "janus-henderson",
    sourceType: "smartrecruiters",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes: "Not re-verified on 2026-08-12; imported paused until the endpoint is verified.",
    },
    websiteUrl: "https://www.janushenderson.com",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/DWF",
    configuration: { smartRecruitersCompany: "DWF" },
    crawlFrequencyMinutes: 2880,
    directorySectorKey: "law",
    industry: "Legal",
    name: "DWF",
    slug: "dwf",
    sourceType: "smartrecruiters",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes: "Not re-verified on 2026-08-12; imported paused until the endpoint is verified.",
    },
    websiteUrl: "https://dwfgroup.com",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/Fieldfisher",
    configuration: { smartRecruitersCompany: "Fieldfisher" },
    crawlFrequencyMinutes: 2880,
    directorySectorKey: "law",
    industry: "Legal",
    name: "Fieldfisher",
    slug: "fieldfisher",
    sourceType: "smartrecruiters",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes: "Not re-verified on 2026-08-12; imported paused until the endpoint is verified.",
    },
    websiteUrl: "https://www.fieldfisher.com",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/Trowers",
    configuration: { smartRecruitersCompany: "Trowers" },
    crawlFrequencyMinutes: 2880,
    directorySectorKey: "law",
    industry: "Legal",
    name: "Trowers & Hamlins",
    slug: "trowers",
    sourceType: "smartrecruiters",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes: "Not re-verified on 2026-08-12; imported paused until the endpoint is verified.",
    },
    websiteUrl: "https://www.trowers.com",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/Mitie",
    configuration: { smartRecruitersCompany: "Mitie" },
    crawlFrequencyMinutes: 2880,
    directorySectorKey: "management_operations",
    industry: "Facilities Management",
    name: "Mitie",
    slug: "mitie",
    sourceType: "smartrecruiters",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes: "Not re-verified on 2026-08-12; imported paused until the endpoint is verified.",
    },
    websiteUrl: "https://www.mitie.com",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/Serco",
    configuration: { smartRecruitersCompany: "Serco" },
    crawlFrequencyMinutes: 2880,
    directorySectorKey: "management_operations",
    industry: "Public Services",
    name: "Serco",
    slug: "serco",
    sourceType: "smartrecruiters",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes: "Not re-verified on 2026-08-12; imported paused until the endpoint is verified.",
    },
    websiteUrl: "https://www.serco.com",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/ITV",
    configuration: { smartRecruitersCompany: "ITV" },
    crawlFrequencyMinutes: 2880,
    directorySectorKey: "marketing_media_pr",
    industry: "Media",
    name: "ITV",
    slug: "itv",
    sourceType: "smartrecruiters",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes: "Not re-verified on 2026-08-12; imported paused until the endpoint is verified.",
    },
    websiteUrl: "https://www.itv.com",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/IQVIA",
    configuration: { smartRecruitersCompany: "IQVIA" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "pharmaceuticals_science",
    industry: "Life Sciences",
    name: "IQVIA",
    slug: "iqvia",
    sourceType: "smartrecruiters",
    verification: {
      status: "stale",
      date: "2026-08-12",
      notes:
        "Stale 2026-08-12: official SmartRecruiters postings API returns 200 with zero postings for this identifier. Paused until a valid official endpoint is verified.",
    },
    websiteUrl: "https://www.iqvia.com",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/NSPCC",
    configuration: { smartRecruitersCompany: "NSPCC" },
    crawlFrequencyMinutes: 2880,
    directorySectorKey: "public_sector_charity",
    industry: "Charity",
    name: "NSPCC",
    slug: "nspcc",
    sourceType: "smartrecruiters",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes: "Not re-verified on 2026-08-12; imported paused until the endpoint is verified.",
    },
    websiteUrl: "https://www.nspcc.org.uk",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/Oxfam",
    configuration: { smartRecruitersCompany: "Oxfam" },
    crawlFrequencyMinutes: 2880,
    directorySectorKey: "public_sector_charity",
    industry: "Charity",
    name: "Oxfam",
    slug: "oxfam",
    sourceType: "smartrecruiters",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes: "Not re-verified on 2026-08-12; imported paused until the endpoint is verified.",
    },
    websiteUrl: "https://www.oxfam.org.uk",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/BritishRedCross",
    configuration: { smartRecruitersCompany: "BritishRedCross" },
    crawlFrequencyMinutes: 2880,
    directorySectorKey: "public_sector_charity",
    industry: "Charity",
    name: "British Red Cross",
    slug: "british-red-cross",
    sourceType: "smartrecruiters",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes: "Not re-verified on 2026-08-12; imported paused until the endpoint is verified.",
    },
    websiteUrl: "https://www.redcross.org.uk",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/PageGroup",
    configuration: { smartRecruitersCompany: "PageGroup" },
    crawlFrequencyMinutes: 2880,
    directorySectorKey: "sales_recruitment_commercial",
    industry: "Recruitment",
    name: "PageGroup",
    slug: "pagegroup",
    sourceType: "smartrecruiters",
    verification: {
      status: "stale",
      date: "2026-08-12",
      notes:
        "Stale 2026-08-12: official SmartRecruiters postings API returns 200 with zero postings for this identifier. Paused until a valid official endpoint is verified.",
    },
    websiteUrl: "https://www.page.com",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/Hays",
    configuration: { smartRecruitersCompany: "Hays" },
    crawlFrequencyMinutes: 2880,
    directorySectorKey: "sales_recruitment_commercial",
    industry: "Recruitment",
    name: "Hays",
    slug: "hays",
    sourceType: "smartrecruiters",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes: "Not re-verified on 2026-08-12; imported paused until the endpoint is verified.",
    },
    websiteUrl: "https://www.hays.co.uk",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/Adecco",
    configuration: { smartRecruitersCompany: "Adecco" },
    crawlFrequencyMinutes: 2880,
    directorySectorKey: "sales_recruitment_commercial",
    industry: "Recruitment",
    name: "Adecco",
    slug: "adecco",
    sourceType: "smartrecruiters",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes: "Not re-verified on 2026-08-12; imported paused until the endpoint is verified.",
    },
    websiteUrl: "https://www.adecco.co.uk",
  },
  {
    atsProvider: "Greenhouse",
    careersUrl: "https://boards.greenhouse.io/baringa",
    configuration: { greenhouseBoardToken: "baringa" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "consulting",
    industry: "Consulting",
    name: "Baringa",
    slug: "baringa",
    sourceType: "greenhouse",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes: "Not re-verified on 2026-08-12; imported paused until the endpoint is verified.",
    },
    websiteUrl: "https://www.baringa.com",
  },
  {
    atsProvider: "Greenhouse",
    careersUrl: "https://boards.greenhouse.io/keystone",
    configuration: { greenhouseBoardToken: "keystone" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "consulting",
    industry: "Consulting",
    name: "Keystone",
    slug: "keystone",
    sourceType: "greenhouse",
    verification: {
      status: "unverified",
      date: "2026-08-12",
      notes: "Not re-verified on 2026-08-12; imported paused until the endpoint is verified.",
    },
    websiteUrl: "https://keystoneglobalpartners.com",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/Accenture",
    configuration: { smartRecruitersCompany: "Accenture" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "consulting",
    industry: "Consulting",
    name: "Accenture",
    slug: "accenture",
    sourceType: "smartrecruiters",
    verification: {
      status: "stale",
      date: "2026-08-12",
      notes:
        "Stale 2026-08-12: manifest SmartRecruiters identifier is not the current official UK endpoint; the official UK careers page now uses Workday. Paused until a valid public endpoint is implemented.",
    },
    websiteUrl: "https://www.accenture.com",
  },
  {
    atsProvider: "Greenhouse",
    careersUrl: "https://boards.greenhouse.io/deliveroo",
    configuration: { greenhouseBoardToken: "deliveroo" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "consumer_fmcg_retail",
    industry: "Consumer Technology",
    name: "Deliveroo",
    slug: "deliveroo",
    sourceType: "greenhouse",
    verification: {
      status: "stale",
      date: "2026-08-12",
      notes:
        "Stale 2026-08-12: Greenhouse board returned 404; imported paused until a valid official endpoint is implemented.",
    },
    websiteUrl: "https://deliveroo.co.uk",
  },
  {
    atsProvider: "Greenhouse",
    careersUrl: "https://boards.greenhouse.io/shopify",
    configuration: { greenhouseBoardToken: "shopify" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "technology_it",
    industry: "Technology",
    name: "Shopify",
    slug: "shopify",
    sourceType: "greenhouse",
    verification: {
      status: "stale",
      date: "2026-08-12",
      notes:
        "Stale 2026-08-12: Greenhouse board returned 404; imported paused until a valid official endpoint is implemented.",
    },
    websiteUrl: "https://www.shopify.com",
  },
  {
    atsProvider: "Ashby",
    careersUrl: "https://jobs.ashbyhq.com/checkoutcom",
    configuration: { ashbyOrg: "checkoutcom" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "financial_services",
    industry: "Payments Technology",
    name: "Checkout.com",
    slug: "checkout-com",
    sourceType: "ashby",
    verification: {
      status: "stale",
      date: "2026-08-12",
      notes:
        "Stale 2026-08-12: Ashby board returned 404; imported paused until a valid official endpoint is implemented.",
    },
    websiteUrl: "https://www.checkout.com",
  },
  {
    atsProvider: "Greenhouse",
    careersUrl: "https://boards.greenhouse.io/slalom",
    configuration: { greenhouseBoardToken: "slalom" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "consulting",
    industry: "Consulting",
    name: "Slalom",
    slug: "slalom",
    sourceType: "greenhouse",
    verification: {
      status: "stale",
      date: "2026-08-12",
      notes:
        "Stale 2026-08-12: Greenhouse board returned 404; imported paused until a valid official endpoint is implemented.",
    },
    websiteUrl: "https://www.slalom.com",
  },
  {
    atsProvider: "Lever",
    careersUrl: "https://jobs.lever.co/thoughtworks",
    configuration: { leverSite: "thoughtworks" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "consulting",
    industry: "Technology Consulting",
    name: "Thoughtworks",
    slug: "thoughtworks",
    sourceType: "lever",
    verification: {
      status: "stale",
      date: "2026-08-12",
      notes:
        "Stale 2026-08-12: Lever postings returned 404; imported paused until a valid official endpoint is implemented.",
    },
    websiteUrl: "https://www.thoughtworks.com",
  },
  {
    atsProvider: "Greenhouse",
    careersUrl: "https://boards.greenhouse.io/asos",
    configuration: { greenhouseBoardToken: "asos" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "consumer_fmcg_retail",
    industry: "Retail",
    name: "ASOS",
    slug: "asos",
    sourceType: "greenhouse",
    verification: {
      status: "stale",
      date: "2026-08-12",
      notes:
        "Stale 2026-08-12: Greenhouse board returned 404; imported paused until a valid official endpoint is implemented.",
    },
    websiteUrl: "https://www.asos.com",
  },
  {
    atsProvider: "Greenhouse",
    careersUrl: "https://boards.greenhouse.io/arup",
    configuration: { greenhouseBoardToken: "arup" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "engineering_energy_infrastructure",
    industry: "Engineering",
    name: "Arup",
    slug: "arup",
    sourceType: "greenhouse",
    verification: {
      status: "stale",
      date: "2026-08-12",
      notes:
        "Stale 2026-08-12: Greenhouse board returned 404; imported paused until a valid official endpoint is implemented.",
    },
    websiteUrl: "https://www.arup.com",
  },
  {
    atsProvider: "Greenhouse",
    careersUrl: "https://boards.greenhouse.io/sky",
    configuration: { greenhouseBoardToken: "sky" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "marketing_media_pr",
    industry: "Media",
    name: "Sky",
    slug: "sky",
    sourceType: "greenhouse",
    verification: {
      status: "stale",
      date: "2026-08-12",
      notes:
        "Stale 2026-08-12: Greenhouse board returned 404; imported paused until a valid official endpoint is implemented.",
    },
    websiteUrl: "https://www.sky.com",
  },
  {
    atsProvider: "Greenhouse",
    careersUrl: "https://boards.greenhouse.io/dentons",
    configuration: { greenhouseBoardToken: "dentons" },
    crawlFrequencyMinutes: 2880,
    directorySectorKey: "law",
    industry: "Legal",
    name: "Dentons",
    slug: "dentons",
    sourceType: "greenhouse",
    verification: {
      status: "stale",
      date: "2026-08-12",
      notes:
        "Stale 2026-08-12: Greenhouse board returned 404; imported paused until a valid official endpoint is implemented.",
    },
    websiteUrl: "https://www.dentons.com",
  },
  {
    atsProvider: "SmartRecruiters",
    careersUrl: "https://www.smartrecruiters.com/Save-the-Children",
    configuration: { smartRecruitersCompany: "Save the Children" },
    crawlFrequencyMinutes: 2880,
    directorySectorKey: "public_sector_charity",
    industry: "Charity",
    name: "Save the Children",
    slug: "save-the-children",
    sourceType: "smartrecruiters",
    verification: {
      status: "stale",
      date: "2026-08-12",
      notes:
        "Stale 2026-08-12: SmartRecruiters postings returned 400; imported paused until a valid official endpoint is implemented.",
    },
    websiteUrl: "https://www.savethechildren.org.uk",
  },
  {
    atsProvider: "Lever",
    careersUrl: "https://jobs.lever.co/skyscanner",
    configuration: { leverSite: "skyscanner" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "technology_it",
    industry: "Travel Technology",
    name: "Skyscanner",
    slug: "skyscanner",
    sourceType: "lever",
    verification: {
      status: "stale",
      date: "2026-08-12",
      notes:
        "Stale 2026-08-12: Lever postings returned 404; imported paused until a valid official endpoint is implemented.",
    },
    websiteUrl: "https://www.skyscanner.net",
  },
  {
    atsProvider: "Greenhouse",
    careersUrl: "https://boards.greenhouse.io/bumble",
    configuration: { greenhouseBoardToken: "bumble" },
    crawlFrequencyMinutes: 1440,
    directorySectorKey: "technology_it",
    industry: "Consumer Technology",
    name: "Bumble",
    slug: "bumble",
    sourceType: "greenhouse",
    verification: {
      status: "stale",
      date: "2026-08-12",
      notes:
        "Stale 2026-08-12: Greenhouse board returned 404; imported paused until a valid official endpoint is implemented.",
    },
    websiteUrl: "https://bumble.com",
  },
];
