/**
 * Deterministic UK city and major-town names used by location admission and
 * HTML location extraction. The list covers every official UK city plus the
 * major towns of England, Scotland, Wales and Northern Ireland. Matching uses
 * word boundaries, and callers must combine city matches with foreign-place
 * signals so same-named cities abroad (Perth, Birmingham, Cambridge, Boston,
 * ...) are not misclassified as UK.
 */

export const ukCityNames: readonly string[] = [
  // England - official cities
  "bath",
  "birmingham",
  "bradford",
  "brighton",
  "brighton and hove",
  "bristol",
  "cambridge",
  "canterbury",
  "carlisle",
  "chelmsford",
  "chester",
  "chichester",
  "colchester",
  "coventry",
  "derby",
  "doncaster",
  "durham",
  "ely",
  "exeter",
  "gloucester",
  "hereford",
  "hove",
  "hull",
  "kingston upon hull",
  "lancaster",
  "leeds",
  "leicester",
  "lichfield",
  "lincoln",
  "liverpool",
  "london",
  "manchester",
  "milton keynes",
  "newcastle",
  "newcastle upon tyne",
  "norwich",
  "nottingham",
  "oxford",
  "peterborough",
  "plymouth",
  "portsmouth",
  "preston",
  "ripon",
  "salford",
  "salisbury",
  "sheffield",
  "southampton",
  "southend",
  "southend-on-sea",
  "st albans",
  "stoke",
  "stoke-on-trent",
  "sunderland",
  "truro",
  "wakefield",
  "wells",
  "westminster",
  "winchester",
  "wolverhampton",
  "worcester",
  "york",
  // England - major towns
  "aldershot",
  "andover",
  "ashford",
  "aylesbury",
  "banbury",
  "barrow-in-furness",
  "barrow in furness",
  "basildon",
  "basingstoke",
  "bedford",
  "bishop auckland",
  "blackburn",
  "blackpool",
  "bolton",
  "bournemouth",
  "bridgwater",
  "bromley",
  "burnley",
  "burton-on-trent",
  "burton upon trent",
  "camberley",
  "cannock",
  "chatham",
  "cheltenham",
  "cirencester",
  "crawley",
  "crewe",
  "croydon",
  "dartford",
  "darlington",
  "dover",
  "eastbourne",
  "eastleigh",
  "epsom",
  "fareham",
  "farnborough",
  "folkestone",
  "gillingham",
  "gosport",
  "gravesend",
  "great yarmouth",
  "grimsby",
  "guildford",
  "harrogate",
  "hartlepool",
  "hastings",
  "hemel hempstead",
  "high wycombe",
  "hitchin",
  "huntingdon",
  "ipswich",
  "kendal",
  "kingston upon thames",
  "kings lynn",
  "leamington spa",
  "lewes",
  "lowestoft",
  "luton",
  "macclesfield",
  "maidenhead",
  "maidstone",
  "margate",
  "middlesbrough",
  "newbury",
  "newcastle-under-lyme",
  "newcastle under lyme",
  "newton aycliffe",
  "northampton",
  "nuneaton",
  "penrith",
  "poole",
  "ramsgate",
  "reading",
  "redcar",
  "rochester",
  "rochdale",
  "rugby",
  "scarborough",
  "scunthorpe",
  "shrewsbury",
  "slough",
  "stafford",
  "stevenage",
  "stockport",
  "stockton-on-tees",
  "stockton on tees",
  "stratford-upon-avon",
  "stratford upon avon",
  "sutton",
  "swindon",
  "tamworth",
  "taunton",
  "telford",
  "tunbridge wells",
  "warrington",
  "warwick",
  "watford",
  "welwyn garden city",
  "weston-super-mare",
  "weston super mare",
  "whitehaven",
  "wigan",
  "witney",
  "woking",
  "workington",
  "worthing",
  "yeovil",
  // Scotland - official cities and major towns
  "aberdeen",
  "airdrie",
  "ayr",
  "cumbernauld",
  "dumfries",
  "dundee",
  "dunfermline",
  "east kilbride",
  "edinburgh",
  "elgin",
  "falkirk",
  "fort william",
  "glasgow",
  "glenrothes",
  "greenock",
  "hamilton",
  "inverness",
  "kilmarnock",
  "kirkcaldy",
  "livingston",
  "motherwell",
  "oban",
  "paisley",
  "perth",
  "st andrews",
  "stirling",
  // Wales - official cities and major towns
  "abergavenny",
  "aberystwyth",
  "bangor",
  "barry",
  "bridgend",
  "caerphilly",
  "cardiff",
  "carmarthen",
  "ebbw vale",
  "llandudno",
  "merthyr tydfil",
  "neath",
  "newport",
  "newtown",
  "pontypridd",
  "port talbot",
  "st asaph",
  "st davids",
  "swansea",
  "wrexham",
  // Northern Ireland - official cities and major towns
  "antrim",
  "armagh",
  "ballymena",
  "belfast",
  "carrickfergus",
  "coleraine",
  "cookstown",
  "craigavon",
  "derry",
  "dungannon",
  "enniskillen",
  "larne",
  "limavady",
  "lisburn",
  "londonderry",
  "newry",
  "newtownabbey",
  "omagh",
  "strabane",
];

const normalizePlace = (value: string): string => value.toLowerCase().replace(/[^a-z0-9]+/gu, " ");

const ukCityNameSet: ReadonlySet<string> = new Set(ukCityNames.map(normalizePlace));

export function ukCityNameIn(text: string): boolean {
  const normalized = ` ${normalizePlace(text)} `;
  for (const city of ukCityNameSet) {
    if (normalized.includes(` ${city} `)) return true;
  }
  return false;
}
