import type { JobDetailRow } from "../../../modules/job-catalog/application/catalog";

/** Deterministic synthetic job detail row for presentation unit tests. */
export function jobDetailFixture(overrides: Partial<JobDetailRow> = {}): JobDetailRow {
  return {
    active: true,
    application_deadline: new Date("2026-12-01T00:00:00Z"),
    application_url: "https://employer.example.com/apply/123",
    career_level_key: "graduate",
    classification_source: "deterministic",
    classification_version: 1,
    company_careers_url: "https://employer.example.com/careers",
    company_employee_band: "10,000–49,999",
    company_has_sponsor: true,
    company_id: "30000000-0000-4000-8000-000000000001",
    company_logo_url: "https://employer.example.com/logo.png",
    company_name: "Example Bank",
    company_ownership_type: "Listed parent/company",
    company_slug: "example-bank",
    company_sponsor_snapshot_date: new Date("2026-08-12T00:00:00Z"),
    company_website_url: "https://employer.example.com",
    degree_requirements: [],
    description_summary: "Support relationship managers and analyse corporate credit risk.",
    eligibility_evidence: null,
    eligibility_reasons: [],
    eligibility_status: "eligible",
    employer_industry_key: "financial_services",
    employment_type: "full_time",
    enrichment_model: null,
    enrichment_version: null,
    experience_requirements: null,
    external_job_id: "req-123",
    first_seen_at: new Date("2026-08-01T00:00:00Z"),
    id: "30000000-0000-4000-8000-000000000002",
    job_function_key: "finance_accounting",
    job_subfunction_key: "audit",
    last_changed_at: new Date("2026-08-01T00:00:00Z"),
    last_seen_at: new Date("2026-08-09T00:00:00Z"),
    last_successful_check_at: null,
    location_text: "London",
    locations: [
      {
        city: "London",
        country: "United Kingdom",
        hybrid: false,
        on_site: true,
        region: "London",
        remote: false,
        source_text: "London",
      },
    ],
    normalized_title: "Graduate Analyst",
    opportunity_type: "graduate_scheme",
    posted_at: new Date("2026-08-01T00:00:00Z"),
    preferred_skills: [],
    publication_status: "published",
    remote_type: "on_site",
    requirements: [],
    responsibilities: [],
    salary_currency: "GBP",
    salary_max: 35_000,
    salary_min: 30_000,
    salary_period: "year",
    sector_key: "financial_services",
    seniority_level: "graduate",
    skills: [],
    slug: "example-bank-graduate-analyst",
    source_url: "https://employer.example.com/jobs/123",
    subsector_key: "retail_corporate_banking",
    title: "Graduate Analyst",
    updated_at: new Date("2026-08-01T00:00:00Z"),
    visa_sponsorship_evidence: null,
    visa_sponsorship_status: "unknown",
    ...overrides,
  };
}

/**
 * A publicly valid but thin role: only the title and official application URL,
 * with no other stored factual value.
 */
export function thinJobFixture(overrides: Partial<JobDetailRow> = {}): JobDetailRow {
  return jobDetailFixture({
    application_deadline: null,
    description_summary: null,
    employment_type: null,
    experience_requirements: null,
    location_text: null,
    locations: [],
    normalized_title: null,
    opportunity_type: "unknown",
    posted_at: null,
    preferred_skills: [],
    remote_type: null,
    requirements: [],
    responsibilities: [],
    salary_currency: null,
    salary_max: null,
    salary_min: null,
    salary_period: null,
    sector_key: null,
    skills: [],
    subsector_key: null,
    visa_sponsorship_status: "unknown",
    ...overrides,
  });
}
